export default function getTransData() {

    //simulate a api data
    const data = [
        {
            id: 1,
            accountNum : 111,
            date: "06-01-2022",
            name: "John",
            amount: 110,
        },
        {
            id: 2,
            accountNum : 111,
            date: "06-02-2022",
            name: "John",
            amount: 90,
        },
        {
            id: 3,
            accountNum : 111,
            date: "06-03-2022",
            name: "John",
            amount: 120,
        },
        {
            id: 4,
            accountNum : 111,
            date: "07-01-2022",
            name: "John",
            amount: 130,
        },
        {
            id: 5,
            accountNum : 111,
            date: "07-02-2022",
            name: "John",
            amount: 210,
        },
        {
            id: 6,
            accountNum : 111,
            date: "07-03-2022",
            name: "John",
            amount: 60,
        },
        {
            id: 7,
            accountNum : 111,
            date: "08-01-2022",
            name: "John",
            amount: 110,
        },
        {
            id: 8,
            accountNum : 111,
            date: "08-02-2022",
            name: "John",
            amount: 150,
        },
        {
            id: 9,
            accountNum : 111,
            date: "08-03-2022",
            name: "John",
            amount: 130,
        }, 
        {
            id: 10,
            accountNum : 222,
            date: "06-01-2022",
            name: "Frank",
            amount: 130,
        },
        {
            id: 11,
            accountNum : 222,
            date: "06-02-2022",
            name: "Frank",
            amount: 190,
        },
        {
            id: 12,
            accountNum : 222,
            date: "06-03-2022",
            name: "Frank",
            amount: 140,
        },
        {
            id: 13,
            accountNum : 222,
            date: "07-01-2022",
            name: "Frank",
            amount: 230,
        },
        {
            id: 14,
            accountNum : 222,
            date: "07-02-2022",
            name: "Frank",
            amount: 110,
        },
        {
            id: 15,
            accountNum : 222,
            date: "07-03-2022",
            name: "Frank",
            amount: 60,
        },
        {
            id: 16,
            accountNum : 222,
            date: "08-01-2022",
            name: "Frank",
            amount: 80,
        },
        {
            id: 17,
            accountNum : 222,
            date: "08-02-2022",
            name: "Frank",
            amount: 210,
        },
        {
            id: 18,
            accountNum : 222,
            date: "08-03-2022",
            name: "Frank",
            amount: 180,
        },
        {
            id: 19,
            accountNum : 333,
            date: "06-01-2022",
            name: "Bill",
            amount: 120,
        },
        {
            id: 20,
            accountNum : 333,
            date: "06-02-2022",
            name: "Bill",
            amount: 90,
        },
        {
            id: 21,
            accountNum : 333,
            date: "06-03-2022",
            name: "Bill",
            amount: 170,
        },
        {
            id: 22,
            accountNum : 333,
            date: "07-01-2022",
            name: "Bill",
            amount: 230,
        },
        {
            id: 23,
            accountNum : 333,
            date: "07-02-2022",
            name: "Bill",
            amount: 150,
        },
        {
            id: 24,
            accountNum : 333,
            date: "07-03-2022",
            name: "Bill",
            amount: 160,
        },
        {
            id: 25,
            accountNum : 333,
            date: "08-01-2022",
            name: "Bill",
            amount: 120,
        },
        {
            id: 26,
            accountNum : 333,
            date: "08-02-2022",
            name: "Bill",
            amount: 300,
        },
        {
            id: 27,
            accountNum : 333,
            date: "08-03-2022",
            name: "Bill",
            amount: 150,
        }, 
    ]

    return Promise.resolve(data);
};